// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatrixServices.Betting.Infrastructure;

#nullable disable

namespace NatrixServices.Migrations.BettingStorageMigrations
{
    [DbContext(typeof(BettingStorage))]
    [Migration("20260626155007_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("NatrixServices.Betting.Core.Entities.Bet", b =>
                {
                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Stake")
                        .HasColumnType("INTEGER");

                    b.HasKey("Owner", "MatchId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("NatrixServices.Betting.Core.Entities.Match", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Player2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("MatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("NatrixServices.Betting.Core.Entities.UserData", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<float>("Balance")
                        .HasColumnType("REAL");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NatrixServices.Betting.Core.Entities.Bet", b =>
                {
                    b.OwnsOne("NatrixServices.Betting.Core.Entities.MatchResult", "ExpectedResult", b1 =>
                        {
                            b1.Property<string>("BetOwner")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BetMatchId")
                                .HasColumnType("TEXT");

                            b1.Property<uint>("Player1")
                                .HasColumnType("INTEGER");

                            b1.Property<uint>("Player2")
                                .HasColumnType("INTEGER");

                            b1.HasKey("BetOwner", "BetMatchId");

                            b1.ToTable("Bets");

                            b1.WithOwner()
                                .HasForeignKey("BetOwner", "BetMatchId");
                        });

                    b.Navigation("ExpectedResult")
                        .IsRequired();
                });

            modelBuilder.Entity("NatrixServices.Betting.Core.Entities.Match", b =>
                {
                    b.OwnsOne("NatrixServices.Betting.Core.Entities.MatchResult", "Result", b1 =>
                        {
                            b1.Property<string>("MatchId")
                                .HasColumnType("TEXT");

                            b1.Property<uint>("Player1")
                                .HasColumnType("INTEGER");

                            b1.Property<uint>("Player2")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.OwnsOne("NatrixServices.Betting.Core.Entities.MatchOdds", "Odds", b1 =>
                        {
                            b1.Property<string>("MatchId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Draw")
                                .HasColumnType("REAL");

                            b1.Property<float>("Player1")
                                .HasColumnType("REAL");

                            b1.Property<float>("Player2")
                                .HasColumnType("REAL");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Odds")
                        .IsRequired();

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
