// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatrixServices.Chess.Infrastructure;

#nullable disable

namespace NatrixServices.Migrations
{
    [DbContext(typeof(ChessStorage))]
    [Migration("20260626091025_ChessUserAddSkin")]
    partial class ChessUserAddSkin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("NatrixServices.Chess.Core.Entities.ChessEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MaxPlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MinPlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Players")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimePerPlayer")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TotalEventDuration")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("NatrixServices.Chess.Core.Entities.ChessGame", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawOffer")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastMoveTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moves")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NextPlayer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerBlack")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerWhite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeLeftBlack")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeLeftWhite")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimePerPlayer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastClockUpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NatrixServices.Chess.Core.Entities.UserData", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Invites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonsWon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TitleHolder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentsWon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
